=== uedake/aws-api/cdk/spec/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Web System Spec Validation",
    "description": "describe aws resource settings",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "stack",
        "api_name",
        "branch",
        "lambda_func"
    ],
    "properties": {
        "stack": {
            "type": "string",
            "pattern": "^[A-Za-z0-9\\-]+$"
        },
        "api_name": {
            "type": "string",
            "pattern": "^[a-z0-9\\-]+$"
        },
        "branch": {
            "$ref": "#/$defs/branch_dict"
        },
        "s3": {
            "$ref": "#/$defs/s3_dict"
        },
        "apigw": {
            "$ref": "#/$defs/apigw"
        },
        "sns": {
            "$ref": "#/$defs/sns_dict"
        },
        "lambda_func": {
            "$ref": "#/$defs/lambda_dict"
        },
        "batch_func": {
            "$ref": "#/$defs/batch_dict"
        },
        "amplify": {
            "$ref": "#/$defs/amplify_dict"
        },
        "ref": {
            "$ref": "#/$defs/ref"
        },
        "repository_root": {
            "type": "string",
            "pattern": "^https://github\\.com/[a-z0-9\\-]+$",
            "description": "github user url which is used as source of Web App"
        },
        "tags": {
            "$ref": "#/$defs/tag_dict"
        },
        "default_runtime": {
            "type": "string",
            "pattern": "^[A-Za-z0-9_]+$"
        }
    },
    "$defs": {
        "tag_dict": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[A-Za-z0-9_\\-\\.]+$": {
                    "type": "string"
                }
            }
        },
        "branch_dict": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[A-Za-z0-9\\-]+$": {
                    "$ref": "#/$defs/branch"
                }
            }
        },
        "branch": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "apigw_stage"
            ],
            "properties": {
                "apigw_stage": {
                    "type": "string",
                    "pattern": "^\\$?[A-Za-z0-9]+$"
                },
                "amplify_type": {
                    "type": "string"
                },
                "bucket": {
                    "type": "string",
                    "pattern": "^[A-Za-z0-9\\-\\.]+$"
                },
                "notification-url": {
                    "type": "string"
                }
            }
        },
        "s3_dict": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[a-z0-9\\-\\.]+$": {
                    "$ref": "#/$defs/s3"
                }
            }
        },
        "s3": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "public_read": {
                    "type": "boolean"
                },
                "website_hosting": {
                    "type": "boolean"
                }
            }
        },
        "apigw": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "lambda_integration"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "lambda_integration": {
                    "$ref": "#/$defs/lambda_integration_dict"
                }
            }
        },
        "lambda_integration_dict": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[A-Za-z0-9_]+$": {
                    "$ref": "#/$defs/lambda_integration"
                }
            }
        },
        "lambda_integration": {
            "type": "object",
            "additionalProperties": false,
            "oneOf": [
                {
                    "required": [
                        "route"
                    ]
                },
                {
                    "required": [
                        "route_openapi"
                    ]
                }
            ],
            "properties": {
                "cognito_auth": {
                    "type": "object",
                    "additionalProperties": false,
                    "required": [
                        "user",
                        "app"
                    ],
                    "properties": {
                        "user": {
                            "type": "string"
                        },
                        "app": {
                            "type": "string",
                            "pattern": "^[A-Za-z0-9\\-]+$"
                        }
                    }
                },
                "route": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "description": "route definition e.g. GET /func_name/{path_param_name}"
                    }
                },
                "route_openapi": {
                    "type": "string",
                    "description": "path to openapi definition yaml"
                }
            }
        },
        "sqs": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "additional_timeout": {
                    "type": "number"
                }
            }
        },
        "sns_dict": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[A-Za-z0-9_\\-]+$": {
                    "$ref": "#/$defs/sns"
                }
            }
        },
        "sns": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "description": {
                    "type": "string"
                },
                "lambda_func": {
                    "$ref": "#/$defs/lambda_dict"
                }
            }
        },
        "lambda_dict": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[A-Za-z0-9_]+$": {
                    "$ref": "#/$defs/lambda"
                }
            }
        },
        "lambda": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "runtime": {
                    "type": "string",
                    "pattern": "^[A-Za-z0-9_]+$"
                },
                "code": {
                    "type": "string"
                },
                "timeout": {
                    "type": "number"
                },
                "queue": {
                    "$ref": "#/$defs/sqs"
                },
                "queue_next": {
                    "type": "string",
                    "pattern": "^[A-Za-z0-9_]+$"
                },
                "layer_list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "batch_dict": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[A-Za-z0-9_]+$": {
                    "$ref": "#/$defs/batch"
                }
            }
        },
        "batch": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "queue_state_lambda": {
                    "type": "string",
                    "pattern": "^[A-Za-z0-9_]+$"
                },
                "maxv_cpus": {
                    "type": "number"
                },
                "memory": {
                    "type": "number"
                },
                "vcpu": {
                    "type": "number"
                }
            }
        },
        "amplify_dict": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[A-Za-z0-9\\-]+$": {
                    "$ref": "#/$defs/amplify"
                }
            }
        },
        "amplify": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "domain"
            ],
            "properties": {
                "domain": {
                    "type": "string",
                    "pattern": "^[a-z0-9\\-\\.]+$"
                },
                "cognito_auth": {
                    "type": "string"
                },
                "deploy_event_sns": {
                    "type": "string",
                    "pattern": "^[A-Za-z0-9_\\-]+$"
                },
                "description": {
                    "type": "string"
                }
            }
        },
        "ref": {
            "type": "object",
            "description": "refered resources. they should be created in advance",
            "additionalProperties": false,
            "properties": {
                "lambda_layer": {
                    "$ref": "#/$defs/layer_dict"
                },
                "vpc": {
                    "$ref": "#/$defs/vpc"
                },
                "cognito": {
                    "$ref": "#/$defs/cognito_dict"
                }
            }
        },
        "cognito_dict": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[A-Za-z0-9_]+$": {
                    "$ref": "#/$defs/cognito"
                }
            }
        },
        "cognito": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "user_pool_id"
            ],
            "properties": {
                "user_pool_id": {
                    "type": "string"
                }
            }
        },
        "layer_dict": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[A-Za-z0-9_]+$": {
                    "type": "string",
                    "description": "layer name without version or layer arn",
                    "pattern": "^[A-Za-z0-9_\\-:]+$"
                }
            }
        },
        "vpc": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "subnet_id_list",
                "security_group_id"
            ],
            "properties": {
                "subnet_id_list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "security_group_id": {
                    "type": "string"
                }
            }
        }
    }
}

=== uedake/aws-api/cdk/spec/sample-api/api_spec.json
{
    "stack": "sample-api-stack",
    "api_name": "sample-api",
    "repository_root": "https://github.com/uedake",
    "tags": {
        "tag_key": "tag_val"
    },
    "default_runtime": "PYTHON_3_13",
    "branch": {
        "main": {
            "apigw_stage": "$default",
            "bucket": "{$api_name}-{$account}",
            "amplify_type": "BETA"
        },
        "dev": {
            "apigw_stage": "dev",
            "bucket": "{$api_name}-{$account}",
            "amplify_type": "DEVELOPMENT"
        },
        "test": {
            "apigw_stage": "test",
            "bucket": "{$api_name}-test-{$account}",
            "amplify_type": "EXPERIMENTAL"
        }
    },
    "s3": {
        "{$api_name}-{$account}": {
            "public_read": false
        },
        "{$api_name}-test-{$account}": {
            "public_read": false
        }
    },
    "apigw": {
        "description": "api for calling sample lambdas",
        "lambda_integration": {
            "pipeline_entry": {
                "route": [
                    "ANY /pipeline_entry",
                    "ANY /pipeline_entry/{z}"
                ]
            },
            "s3_access": {
                "route_openapi": "src_lambda/s3_access/openapi.yaml"
            },
            "echo_with_auth": {
                "cognito_auth": {
                    "user": "developer",
                    "app": "aws-sample-app"
                },
                "route": [
                    "ANY /echo_with_auth/{path1}/{path2}",
                    "ANY /echo_with_auth/{path1}",
                    "ANY /echo_with_auth"
                ]
            },
            "echo": {
                "route": [
                    "ANY /echo/{path1}/{path2}",
                    "ANY /echo/{path1}",
                    "ANY /echo"
                ]
            },
            "numpy": {
                "route": [
                    "ANY /numpy",
                    "ANY /numpy/{z}"
                ]
            }
        }
    },
    "sns": {
        "amplify_state_change": {
            "description": "CI/CD用",
            "lambda_func": {
                "notify_teams": {
                    "code": "src_lambda/notify_teams/src",
                    "timeout": 3
                }
            }
        }
    },
    "lambda_func": {
        "pipeline_entry": {
            "code": "src_lambda/pipeline_entry/src",
            "timeout": 3,
            "queue_next": "pipeline_process"
        },
        "pipeline_process": {
            "code": "src_lambda/pipeline_process/src",
            "timeout": 10,
            "queue": {
                "additional_timeout": 10
            }
        },
        "s3_access": {
            "code": "src_lambda/s3_access/src",
            "timeout": 10
        },
        "echo": {
            "code": "src_lambda/echo/src",
            "timeout": 3
        },
        "echo_with_auth": {
            "code": "src_lambda/echo/src",
            "timeout": 3
        },
        "called_by_batch": {
            "code": "src_lambda/called_by_batch/src",
            "timeout": 3
        },
        "numpy": {
            "code": "src_lambda/numpy/src",
            "timeout": 3,
            "layer_list": [
                "pandas_python313"
            ]
        }
    },
    "batch_func": {
        "convert": {
            "queue_state_lambda": "called_by_batch",
            "maxv_cpus": 40,
            "memory": 8192,
            "vcpu": 4
        }
    },
    "amplify": {
        "aws-sample-app": {
            "description": "サンプルアプリ",
            "cognito_auth": "developer",
            "domain": "wal-test.com",
            "deploy_event_sns": "amplify_state_change"
        }
    },
    "ref": {
        "lambda_layer": {
            "pandas_python313": "arn:aws:lambda:ap-northeast-1:336392948345:layer:AWSSDKPandas-Python313:4",
            "pandas_python312": "arn:aws:lambda:ap-northeast-1:336392948345:layer:AWSSDKPandas-Python312:19"
        },
        "vpc": {
            "subnet_id_list": [],
            "security_group_id": ""
        },
        "cognito": {
            "developer": {
                "user_pool_id": "ap-northeast-1_kw2EVel03"
            }
        }
    }
}
