=== uedake/aws-api/cdk/api_spec/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "API spec Validation",
    "description": "api spec setting",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "name"
    ],
    "properties": {
        "name": {
            "type": "string",
            "pattern": "^[A-z0-9-]+$"
        },
        "default_runtime": {
            "type": "string",
            "pattern": "^[A-z0-9_]+$"
        },
        "stage": {
            "$ref": "#/$defs/stage_dict"
        },
        "s3": {
            "$ref": "#/$defs/s3_dict"
        },
        "apigw": {
            "$ref": "#/$defs/apigw"
        },
        "sns": {
            "$ref": "#/$defs/sns_dict"
        },
        "lambda_func": {
            "$ref": "#/$defs/lambda_dict"
        },
        "batch_func": {
            "$ref": "#/$defs/batch_dict"
        },
        "ref": {
            "$ref": "#/$defs/ref"
        }
    },
    "$defs": {
        "stage_dict": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^\\$?[A-z0-9]+$": {
                    "$ref": "#/$defs/stage"
                }
            }
        },
        "stage": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "branch"
            ],
            "properties": {
                "branch": {
                    "type": "string"
                },
                "bucket": {
                    "type": "string",
                    "pattern": "^[A-z0-9\\-\\.]+$"
                },
                "notification-url": {
                    "type": "string"
                }
            }
        },
        "s3_dict": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[A-Za-z0-9\\-\\.]+$": {
                    "$ref": "#/$defs/s3"
                }
            }
        },
        "s3": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "public_read": {
                    "type": "boolean"
                },
                "website_hosting": {
                    "type": "boolean"
                }
            }
        },
        "apigw": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "route"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "route": {
                    "$ref": "#/$defs/route_dict"
                }
            }
        },
        "route_dict": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[A-z0-9_]+$": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "description": "route key e.g. GET /func_name/{path_param_name}"
                    }
                }
            }
        },
        "sqs": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "additional_timeout": {
                    "type": "number"
                }
            }
        },
        "sns_dict": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[A-z0-9_]+$": {
                    "$ref": "#/$defs/sns"
                }
            }
        },
        "sns": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "description": {
                    "type": "string"
                },
                "lambda": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "lambda_dict": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[A-z0-9_]+$": {
                    "$ref": "#/$defs/lambda"
                }
            }
        },
        "lambda": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "runtime": {
                    "type": "string",
                    "pattern": "^[A-z0-9_]+$"
                },
                "code": {
                    "type": "string"
                },
                "timeout": {
                    "type": "number"
                },
                "queue": {
                    "$ref": "#/$defs/sqs"
                },
                "queue_next": {
                    "type": "string",
                    "pattern": "^[A-z0-9_]+$"
                },
                "layer_list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "batch_dict": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[A-z0-9_]+$": {
                    "$ref": "#/$defs/batch"
                }
            }
        },
        "batch": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "queue_state_lambda": {
                    "type": "string",
                    "pattern": "^[A-z0-9_]+$"
                },
                "maxv_cpus": {
                    "type": "number"
                },
                "memory": {
                    "type": "number"
                },
                "vcpu": {
                    "type": "number"
                }
            }
        },
        "ref": {
            "type": "object",
            "description": "refered resources. they should be created in advance",
            "additionalProperties": false,
            "properties": {
                "lambda_layer": {
                    "$ref": "#/$defs/layer_dict"
                },
                "vpc": {
                    "$ref": "#/$defs/vpc"
                }
            }
        },
        "layer_dict": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[A-z0-9_]+$": {
                    "type": "string",
                    "description": "layer name without version or layer arn",
                    "pattern": "^[A-z0-9_\\-:]+$"
                }
            }
        },
        "vpc": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "subnet_id_list",
                "security_group_id"
            ],
            "properties": {
                "subnet_id_list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "security_group_id": {
                    "type": "string"
                }
            }
        }
    }
}

=== uedake/aws-api/cdk/api_spec/sample/api_spec.json
{
    "name": "sample-api",
    "default_runtime": "PYTHON_3_13",
    "stage": {
        "$default": {
            "branch": "main",
            "bucket": "{$account}-{$api}"
        },
        "dev": {
            "branch": "dev",
            "bucket": "{$account}-{$api}"
        },
        "test": {
            "branch": "test",
            "bucket": "{$account}-{$api}-test"
        }
    },
    "s3": {
        "{$account}-{$api}": {
            "public_read": false
        },
        "{$account}-{$api}-test": {
            "public_read": false
        }
    },
    "apigw": {
        "description": "api for calling sample lambdas",
        "route": {
            "pipeline_entry": [
                "ANY /pipeline_entry",
                "ANY /pipeline_entry/{z}"
            ],
            "s3_access": [
                "ANY /s3_access"
            ],
            "echo": [
                "ANY /echo/{path1}/{path2}",
                "ANY /echo/{path1}",
                "ANY /echo"
            ],
            "numpy": [
                "ANY /numpy",
                "ANY /numpy/{z}"
            ]
        }
    },
    "sns": {
        "amplify_state_change": {
            "description": "CI/CDç”¨",
            "lambda": [
                "notify_teams"
            ]
        }
    },
    "lambda_func": {
        "pipeline_entry": {
            "code": "src_lambda/pipeline_entry/src",
            "timeout": 3,
            "queue_next": "pipeline_process"
        },
        "pipeline_process": {
            "code": "src_lambda/pipeline_process/src",
            "timeout": 10,
            "queue": {
                "additional_timeout": 10
            }
        },
        "s3_access": {
            "code": "src_lambda/s3_access/src",
            "timeout": 10
        },
        "echo": {
            "code": "src_lambda/echo/src",
            "timeout": 3,
            "queue": {
                "additional_timeout": 10
            }
        },
        "called_by_batch": {
            "code": "src_lambda/called_by_batch/src",
            "timeout": 3
        },
        "numpy": {
            "code": "src_lambda/numpy/src",
            "timeout": 3,
            "layer_list": [
                "pandas_python313"
            ]
        },
        "notify_teams": {
            "code": "src_lambda/notify_teams/src",
            "timeout": 3
        }
    },
    "batch_func": {
        "convert": {
            "queue_state_lambda": "called_by_batch",
            "maxv_cpus": 40,
            "memory": 8192,
            "vcpu": 4
        }
    },
    "ref": {
        "lambda_layer": {
            "pandas_python313": "arn:aws:lambda:ap-northeast-1:336392948345:layer:AWSSDKPandas-Python313:4",
            "pandas_python312": "arn:aws:lambda:ap-northeast-1:336392948345:layer:AWSSDKPandas-Python312:19"
        },
        "vpc": {
            "subnet_id_list": [],
            "security_group_id": ""
        }
    }
}
